steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_IMAGE
      - --build-arg
      - VITE_CORE_SERVICE_URL=https://estospaces-core-service-prod-zaryfkxmeq-nw.a.run.app
      - --build-arg
      - VITE_BOOKING_SERVICE_URL=https://estospaces-booking-service-prod-zaryfkxmeq-nw.a.run.app
      - --build-arg
      - VITE_PAYMENT_SERVICE_URL=https://estospaces-payment-service-prod-zaryfkxmeq-nw.a.run.app
      - --build-arg
      - VITE_NOTIFICATION_SERVICE_URL=https://estospaces-notification-service-prod-zaryfkxmeq-nw.a.run.app
      - --build-arg
      - VITE_SEARCH_SERVICE_URL=https://estospaces-search-service-prod-zaryfkxmeq-nw.a.run.app
      - --build-arg
      - VITE_MEDIA_SERVICE_URL=https://estospaces-media-service-prod-zaryfkxmeq-nw.a.run.app
      - --build-arg
      - VITE_MESSAGING_SERVICE_URL=https://estospaces-messaging-service-prod-zaryfkxmeq-nw.a.run.app
      - .
images:
  - $_IMAGE
